### ISSUE TITLE
One small issue - this script requires default settings for StableDiffusion-webui

### ISSUE THREAD

**Issue by RobertSvebeck** [memes-forever/Stable-diffusion-webui-video#2]
I had changed some settings in webui like the filename pattern and save folders for images etc and then this script was not working. It is probably demanding default filenames and paths (I think?). But could be other settings also? 

Solution anyway for me was to delete config.json and restart, then it worked.

**Comment by dvztimes** [comment]
I too am having this problem.  Would love it if would honor the file paths entered into Automatic.  Kinda useless as-is.

**Comment by junguler** [comment]
i'm on the latest commit as writing of this comment and it doesn't work at all even if i removed config.json file

**Comment by junguler** [comment]
> i'm on the latest commit as writing of this comment and it doesn't work at all even if i removed config.json file

ok, it seems there was an issue with one of the commits and img2img, it's now fixed as of  https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/52cef36f6ba169a8e606ecdcaed73d47378f0e8e

the original issue still stands tho

because i like my config file i'm going to use ffmpeg for the time being until this issue is fixed
```
cat *.png | ffmpeg -framerate 10 -f image2pipe -i - video.mp4
```

**Comment by memes-forever** [comment]
> I had changed some settings in webui like the filename pattern and save folders for images etc and then this script was not working. It is probably demanding default filenames and paths (I think?). But could be other settings also?
> 
> Solution anyway for me was to delete config.json and restart, then it worked.

fix it, thx
